# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'MLLeaksFinderDemo' do
    use_frameworks!
    pod 'MLeaksFinder', :path => '../'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'MLeaksFinder' or target.name == 'RxSwift'
                target.build_configurations.each do |config|
                    if config.name == 'Debug'
                        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
                    end
                end
            end
        end
    end
end

